TrainingArguments:
  num_train_epochs: 1    # 1
  warmup_steps: 100      # 200
  per_device_train_batch_size: 1    # safe (always works)
  weight_decay: 0.01
  logging_steps: 50
  evaluation_strategy: steps
  eval_steps: 500
  save_steps: 500    # 1e6
  gradient_accumulation_steps: 16

